Config = {}

-- true = use dirty money on blackmarket | false = use bank money on blackmarket
Config.UseDirtyMoneyOnBlackmarket = false

Config.Blackmarket = { -- (item/weapon) / if is weapon then: {"weapon id", true}, if is item then: {"item id", false} (all blackmarket items need to be on the BlacklistItems)
	{"weapon_flashlight", false},
	{"weapon_knife", false},
	{"weapon_machete", false},
	{"weapon_dagger", false},
	{"weapon_switchblade", false},
	{"weapon_hatchet", false},
	{"weapon_nightstick", false},
	{"weapon_hammer", false},
	{"weapon_bat", false},
	{"weapon_golfclub", false},
	{"weapon_bottle", false},
	{"weapon_crowbar", false},
	{"weapon_knuckle", false},
	{"weapon_snspistol", false},
	{"weapon_pistol", false},
	{"weapon_pistol_mk2", false},
	{"weapon_combatpistol", false},
	{"weapon_appistol", false},
	{"weapon_heavypistol", false},
	{"weapon_doubleaction", false},
	{"weapon_pistol50", false},
	{"weapon_microsmg", false},
	{"weapon_machinepistol", false},
	{"weapon_minismg", false},
	{"weapon_combatpdw", false},
	{"weapon_smg", false},
	{"weapon_compactrifle", false},
	{"weapon_assaultrifle", false},
	{"weapon_assaultrifle_mk2", false},
	{"weapon_carbinerifle", false},
	{"weapon_carbinerifle_mk2", false},
	{"weapon_combatmg", false},
	{"weapon_dbshotgun", false},
	{"weapon_pumpshotgun", false},
	{"weapon_sawnoffshotgun", false},
	{"weapon_taser", false},
	{"weapon_sniperrifle", false},
	{"weapon_grenadelauncher_smoke", false},
	{"weapon_firework", false},
	{"weapon_rpg", false},
	{"weapon_railgun", false},
	{"weapon_minigun", false},
	{"weapon_pipebomb", false},
	{"weapon_grenade", false},
	{"weapon_stickybomb", false},
	{"weapon_smokegrenade", false},
	{"weapon_bzgas", false},
	{"weapon_molotov", false},
	{"weapon_fireextinguisher", false},
	{"weapon_petrolcan", false},
	{"weapon_ball", false},
	{"weapon_flare", false},
	{"weapon_snowball", false},
	{"weapon_nailgun", false},
	{"weapon_glock", false},
	{"weapon_browning", false},
	{"weapon_dp9", false},
	{"weapon_microsmg2", false},
	{"weapon_microsmg3", false},
	{"weapon_m4", false},
	{"weapon_katana", false},
	{"weapon_shiv", false},
	{"weapon_book", false},
	{"weapon_cash", false},
	{"weapon_brick", false},
	{"weapon_shoe", false},
	{"pdbadge", false},
	{"dojbadge", false},
	{"stungun_ammo", false},
	{"pistol_ammo", false},
	{"smg_ammo", false},
	{"mg_ammo", false},
	{"shotgun_ammo", false},
	{"rifle_ammo", false},
	{"sniper_ammo", false},
	{"pistol_suppressor", false},
	{"pistol_extendedclip", false},
	{"smg_suppressor", false},
	{"smg_extendedclip", false},
	{"smg_flashlight", false},
	{"smg_scope", false},
	{"rifle_suppressor", false},
	{"rifle_extendedclip", false},
	{"rifle_drummag", false},
	{"ifak", false},
	{"nitrous", false},
	{"tunerlaptop", false},
	{"thermite", false},
	{"thermitecharge", false},
	{"vpn", false},
	{"screwdriverset", false},
	{"cryptostick", false},
	{"tablet", false},
	{"electronickit", false},
	{"gatecrack", false},
	{"trojan_usb", false},
	{"security_card_01", false},
	{"security_card_02", false},
	{"security_card_03", false},
	{"bobcatsecuritycard", false},
	{"drill", false},
	{"red_dongle", false},
	{"yellow_dongle", false},
	{"green_dongle", false},
	{"blue_dongle", false},
	{"advancedscrewdriver", false},
	{"handcuffs", false},
	{"armor", false},
	{"shitlockpick", false},
	{"disabler", false},
	{"pixellaptop", false},
	{"heistlaptop4", false},
	{"heistlaptop3", false},
	{"heistlaptop2", false},
	{"heistlaptop1", false},
	{"cokebaggy", false},
	{"methbag", false},
	{"oxy", false},
	{"weed_white-widow_joint", false},
	{"weed_skunk_joint", false},
	{"weed_purple-haze_joint", false},
	{"weed_og-kush_joint", false},
	{"weed_amnesia_joint", false},
	{"weed_ak47_joint", false},
	{"weed_white-widow", false},
	{"weed_skunk", false},
	{"weed_purple-haze", false},
	{"weed_og-kush", false},
	{"weed_amnesia", false},
	{"weed_ak47", false},
	{"id_card", false},
	{"driver_license", false},
}

Config.BlacklistItems = { -- items/weapons that are not allowed to be sold on normal market
	"id_card",
	"driver_license",
	"cokelabkey",
	"methlabkey",
	"weapon_flashlight",
	"weapon_knife",
	"weapon_machete",
	"weapon_dagger",
	"weapon_switchblade",
	"weapon_hatchet",
	"weapon_nightstick",
	"weapon_hammer",
	"weapon_bat",
	"weapon_golfclub",
	"weapon_bottle",
	"weapon_crowbar",
	"weapon_knuckle",
	"weapon_snspistol",
	"weapon_pistol",
	"weapon_pistol_mk2",
	"weapon_combatpistol",
	"weapon_appistol",
	"weapon_heavypistol",
	"weapon_doubleaction",
	"weapon_pistol50",
	"weapon_microsmg",
	"weapon_machinepistol",
	"weapon_minismg",
	"weapon_combatpdw",
	"weapon_smg",
	"weapon_compactrifle",
	"weapon_assaultrifle",
	"weapon_assaultrifle_mk2",
	"weapon_carbinerifle",
	"weapon_carbinerifle_mk2",
	"weapon_combatmg",
	"weapon_dbshotgun",
	"weapon_pumpshotgun",
	"weapon_sawnoffshotgun",
	"weapon_taser",
	"weapon_sniperrifle",
	"weapon_grenadelauncher_smoke",
	"weapon_firework",
	"weapon_rpg",
	"weapon_railgun",
	"weapon_minigun",
	"weapon_pipebomb",
	"weapon_grenade",
	"weapon_stickybomb",
	"weapon_smokegrenade",
	"weapon_bzgas",
	"weapon_molotov",
	"weapon_fireextinguisher",
	"weapon_petrolcan",
	"weapon_ball",
	"weapon_flare",
	"weapon_snowball",
	"weapon_nailgun",
	"weapon_glock",
	"weapon_browning",
	"weapon_dp9",
	"weapon_microsmg2",
	"weapon_microsmg3",
	"weapon_m4",
	"weapon_katana",
	"weapon_shiv",
	"weapon_book",
	"weapon_cash",
	"weapon_brick",
	"weapon_shoe",
	"pdbadge",
	"dojbadge",
	"stungun_ammo",
	"pistol_ammo",
	"smg_ammo",
	"mg_ammo",
	"shotgun_ammo",
	"rifle_ammo",
	"sniper_ammo",
	"pistol_suppressor",
	"pistol_extendedclip",
	"smg_suppressor",
	"smg_extendedclip",
	"smg_flashlight",
	"smg_scope",
	"rifle_suppressor",
	"rifle_extendedclip",
	"rifle_drummag",
	"ifak",
	"nitrous",
	"tunerlaptop",
	"markedbills",
	"inkedmoneybag",
	"band",
	"rollcash",
	"cashstack",
	"goldbar",
	"goldcoin",
	"diamond_ring",
	"goldchain",
	"rolex",
	"10kgoldchain",
	"thermite",
	"thermitecharge",
	"vpn",
	"screwdriverset",
	"cryptostick",
	"laptop",
	"tablet",
	"electronickit",
	"gatecrack",
	"trojan_usb",
	"security_card_01",
	"security_card_02",
	"security_card_03",
	"bobcatsecuritycard",
	"drill",
	"red_dongle",
	"yellow_dongle",
	"green_dongle",
	"blue_dongle",
	"advancedscrewdriver",
	"licenseplate",
	"handcuffs",
	"armor",
	"shitlockpick",
	"disabler",
	"pixellaptop",
	"heistlaptopprac",
	"heistlaptop4",
	"heistlaptop3",
	"heistlaptop2",
	"heistlaptop1",
	"rawcoke",
	"powdercoke",
	"cokebaggy",
	"coke10g",
	"cokebrick",
	"rawmeth",
	"drymeth",
	"methbag",
	"meth10g",
	"methbrick",
	"oxy",
	"weed_white-widow_joint",
	"weed_skunk_joint",
	"weed_purple-haze_joint",
	"weed_og-kush_joint",
	"weed_amnesia_joint",
	"weed_ak47_joint",
	"weed4g",
	"weed_white-widow",
	"weed_skunk",
	"weed_purple-haze",
	"weed_og-kush",
	"weed_amnesia",
	"weed_ak47",
}

Config.BlacklistVehicles = { -- all vehicles that are not allowed to be sold on the market (check the gameName on vehicles.meta -> <gameName>Supra</gameName>)
	"Supra",
	"M8",
}

-------------------------- DISCORD LOGS
-- To set your Discord Webhook URL go to server.lua, line 2
Config.BotName = 'ElBar Logs' -- Write the desired bot name
Config.ServerName = 'El Bar RP' -- Write your server's name
Config.IconURL = '' -- Insert your desired image link
Config.DateFormat = '%d/%m/%Y [%X]' -- To change the date format check this website - https://www.lua.org/pil/22.1.html

-- To change a webhook color you need to set the decimal value of a color, you can use this website to do that - https://www.mathsisfun.com/hexadecimal-decimal-colors.html
Config.AddAdColor = '6225733'
Config.BuyItemColor = '224'
Config.RemoveAdColor = '16711680'
Config.ClaimAdColor = '12231480'