Config = {}

-- Set how many flags will result in a ban --
Config.FlagsForBan = 5

-- Set values for flags -- 
Config.SuperJumpLength = 20.0
Config.MaxSpeed = 13 

Config.Antiresourcestop = true

-- Set group --
Config.Group = "user"

-- Blacklisted plates --
Config.BlacklistedPlates = {
    "BRUTAN",
}

Config.Webhooks = {
    ["report"] = "https://discord.com/api/webhooks/945871583292059709/nDu2A2uDvZwlu2IC9VeFVzcG5ye-oAKru65CsryJvewOGAKif-_cmIKvm5V_GZFOjUif",
    ["default"] = "https://discord.com/api/webhooks/945871751143895112/sXGyhG_BJUwdI7Sa3WUHfMqgwcFqzy-a2ZPHaIH92UXUjqnJOv4BPtMdCQdNWig4xQRW",
    ["playermoney"] = "https://discord.com/api/webhooks/945871967976820796/Mt7A-F2CkC8ltpsVuxAoSWCZCZr8h6mLk-WgmIyeYlsZH0yNCrC8byQHXyznmA82zDP3",
    ["playerinventory"] = "https://discord.com/api/webhooks/945872068375904287/r4FQvWCcTfnccFs8CMbgFQ640zX6GXqtDAgGgfUaOUWdeHCSvte_29sa8IX10dzKWeKL",
    ["robbing"] = "https://discord.com/api/webhooks/945872188618182707/xyVkb5T5SX_dSfW1GcLJZL9WcAgB7Wbofn_H8qnlcPNbbq4aq0RCGG4JIROTr9Infdtg",
    ["cuffing"] = "https://discord.com/api/webhooks/945872290078396426/g_QI_uJa7pFTDKG3S86aLrOK_GeOBCiVaFGhzZ_1JvvPU3H8XHlKIAhN1ctEjX9w9YnB",
    ["drop"] = "https://discord.com/api/webhooks/945872390213226506/kWx7je6gzNYVE8Q9EKU9yvYTVveSTsQYPn7-xOefCX8PoV5tzFh9A7pmhmHYIQs9BPI_",
    ["trunk"] = "https://discord.com/api/webhooks/945872496845021184/xazUTXQu22vV_x7dSqdHn_sboooUtP-6riRk1GxznwMCqamf1gKmfIvKA30p2WX9zOIP",
    ["stash"] = "https://discord.com/api/webhooks/945872605657825320/6gCGjOqqsQVmWEWOH6k_i0VOrivftxwkZO8vR86tRjJpALO9HHCkfiIfUbTWvG4PuhLL",
    ["glovebox"] = "https://discord.com/api/webhooks/945872703754207232/8EzShgcfUCeTS1dsRMUHMNSZvtCub7oecClfi4YxACJqzJq-J50nztjmuJPXi8A1sfhW",
    ["banking"] = "https://discord.com/api/webhooks/945872805906481172/9ghh65PAlnXCH4Z4EQKCj0xRtQhlRtywJrP2Un7GW1H5AJxEv8cmfDyd8RPVDgl-Ba70",
    ["vehicleshop"] = "https://discord.com/api/webhooks/945872892586000414/1LuX0qWQXDRAsjRjFhwkFsJHuQ20t99uWcrOQRz7jBZ4L0mhW6lkLCqBYBXpz9DcAjO7",
    ["vehicleupgrades"] = "https://discord.com/api/webhooks/945872967345274880/779JJpUp1ZjfgxHAQCCzrSVtezvnfUKeqfjwV1C_H6edFB6_9bo87aQcMK6tBhldqvf1",
    ['varheist'] = "https://discord.com/api/webhooks/931196524606668871/viC5M_Nlai6FmiOCn2v8TpoBHZy7EV6dhWcwQ2wqmLyAyeGagLZb4et9lsK-nS_mhBUY",
    -------------------------Complate--------------------------------
    ["shops"] = "https://discord.com/api/webhooks/900512888555450399/1TNqm-1Vmfl-kE_xnNi6ki6CLCaHFScKAHV2yx_zcu7mCR_MeDPtAQzPrZ72n7bJGJK9",
    ["dealers"] = "https://discord.com/api/webhooks/900513227287433286/bVQRJw1XT3G63mcPvuS70kHaDzQqmDU3nTy51Vgvb9TrNMo05BZhCmzPigRbxFMZzPer",
    ["storerobbery"] = "https://discord.com/api/webhooks/900513434465087499/L7fx2jp_wd8Xpzze_j3ndjecrfGlTQzy0hGVxSsia9Mb3fHKIU7FhgSdaFFqOtZ4I3Il",
    ["bankrobbery"] = "https://discord.com/api/webhooks/900513577973207072/vDn9hl4i3s4TnFKqZ5QXmgNcU6GK9GVLwWCDz0b6kZh_TuBaR-l47XOjjXlVBQaPxkp8",
    ["powerplants"] = "https://discord.com/api/webhooks/900513774254043177/7iDnFUilXtkLjySXgtxl8P0thPJiyIVPb_kgz9PObS_Zq01x_4RXOSz7lvMZYuvYtUSi",
    ["death"] = "https://discord.com/api/webhooks/945873092981457006/dUUFrKZLMWzZR4L09E92rDhy_yU1ApYnA6WeDYocaJhK_BuItEImDwNfI-TdjjI6m7Sg",
    ["joinleave"] = "https://discord.com/api/webhooks/900514087883116614/AlEkZ2YqWZ0KvX9x_bC_uTHlz3DwVwUC6fuONDGJINBTCq84FUUqLhrR_H-fy18LDDXi",
    ["ooc"] = "https://discord.com/api/webhooks/945873290872913960/qgNdGcnp9kztO1XJ3yuYA_UoEpLvBmp-z8R9XkdKEaitwzyS5klTvdzXo0y0jKZWar3l",
    ["me"] = "https://discord.com/api/webhooks/945873290872913960/qgNdGcnp9kztO1XJ3yuYA_UoEpLvBmp-z8R9XkdKEaitwzyS5klTvdzXo0y0jKZWar3l",
    ["pmelding"] = "https://discord.com/api/webhooks/900514526930296872/EZJ2bmZpKHTyIi_tNb8MS3Qm7sugeBi4JGU7WeHJuDmvFKoLgPo6ddrpXjhJOgCXEkQB",
    ["112"] = "https://discord.com/api/webhooks/900514684418027560/ZbqHpc-k252Bz5VDF4MePnyd328Z-ogLAG-Q0fd29HR97DzDS8Xb4M4CKA239Ds-91nI",
    ["bans"] = "https://discord.com/api/webhooks/900514864500461619/OmwKtzEOPEKHsCb0NfIZGoH5P5W4DiFapMfsc05Z5fiiLb95uhBw_0k8qcDkEvZQo5mS",
    ["anticheat"] = "https://discord.com/api/webhooks/900515023544279110/mlYokDfl79ONgwTdyrGK3MW9KeD_lA8pF6Ocorec92XWxzCezWiM0Y-O3mH7BA2tqojc",
    ["weather"] = "https://discord.com/api/webhooks/900515249499815956/yRHufrK8LLt5pnMudipZiaEe0cvUYMoB5kPqWF2nijGxz8aXOKkbm3Adh049NNDs5yfr",
    ["moneysafes"] = "https://discord.com/api/webhooks/900515383189061682/DbwNy9Lm7T-b5LzT84YC96phACavS6Hg5pD28O07KgYsSSaMSu55fRjSn4Ze6A-exdob",
    ["bennys"] = "https://discord.com/api/webhooks/900515516114931764/yx7UUc7jTJ5ogZvNw5YzAQb2mj-BS22-y-krxS28vOk3rpLzGH9BkcAzSMx3E3kuxJ8Y",
    ['bossmenu'] = 'https://discord.com/api/webhooks/929813073500442624/BygUYMNARhGD0tZaeFjiWdbrh3NK01UxSlL2dfHBJwc5J1hAeW2YPrKn2gkwxiurNS8x',
    ['robbery'] = 'https://discord.com/api/webhooks/900515725301653535/Co4Ncp2RZyGkYZ04KtMNwCqoNs5Ks1NBfNWeRusupAduj5b62ES1w47pp6g_JbSHUwmy',
    ['casino'] = 'https://discord.com/api/webhooks/900515877403906048/M8E-cUlFFrngWGP0c-qACBvePGQ4TVtBi9iARj3KHoS4FU-U0lcJVVM32D83lT8E_YxF',
    ['traphouse'] = 'https://discord.com/api/webhooks/929813263875723294/Di5CFZUdN6mXB8ZU3u02BY5q8_0NdmSeL5ZiJNMCuyHgwMtJISTuQqJ3hAEKsdmML051',
    ['911'] = 'https://discord.com/api/webhooks/900514684418027560/ZbqHpc-k252Bz5VDF4MePnyd328Z-ogLAG-Q0fd29HR97DzDS8Xb4M4CKA239Ds-91nI',
    ['palert'] = 'https://discord.com/api/webhooks/900514684418027560/ZbqHpc-k252Bz5VDF4MePnyd328Z-ogLAG-Q0fd29HR97DzDS8Xb4M4CKA239Ds-91nI',
    ['house'] = 'https://discord.com/api/webhooks/929813577387372605/BpfPaIAvKJpI4OidTIlwahdomxyuDZ2K-ipgmqVZ3aQupnJmY8mQMVUDRd3S6hgcpqm4',
    -------------------------------------------------------------------------------------------------------------------------------------------------
    ["policeduty"] = "https://discord.com/api/webhooks/942551603817373736/Yv2pvpshV0LgHLh6ICPNQXsaQNWz4PtwAWgNdqj5oS1VcJBJLoGnG9fDJ244nlB8xbYX",
    ["emsduty"] = "https://discord.com/api/webhooks/942551948824031283/WvnyLX0YJxF_bUehw86FVU7n81OcsjtyqKf43SUDV4PsWHANroKE97cXnz7iGle97s6y",
    ["cardealerduty"] = "https://discord.com/api/webhooks/942552040008200212/VtLPf0upChRqPeWbvU-1nwGizmpLSK9myrYLo1aF5tcT_edmkBkWLc_i0-Qz9zsAejI5",
    ["mechanicduty"] = "https://discord.com/api/webhooks/942552040008200212/VtLPf0upChRqPeWbvU-1nwGizmpLSK9myrYLo1aF5tcT_edmkBkWLc_i0-Qz9zsAejI5",
    ["reporter"] = "https://discord.com/api/webhooks/942552040008200212/VtLPf0upChRqPeWbvU-1nwGizmpLSK9myrYLo1aF5tcT_edmkBkWLc_i0-Qz9zsAejI5",
}

Config.Colors = { -- https://www.spycolor.com/
    ['default'] = 14423100,
    ['blue'] = 255,
    ['red'] = 16711680,
    ['green'] = 65280,
    ['white'] = 16777215,
    ['black'] = 0,
    ['orange'] = 16744192,
    ['yellow'] = 16776960,
    ['pink'] = 16761035,
}

Config.BlacklistedEvents = {
    '211ef2f8-f09c-4582-91d8-087ca2130157',
    '265df2d8-421b-4727-b01d-b92fd6503f5e',
    '6a7af019-2b92-4ec2-9435-8fb9bd031c26',
    '8321hiue89js',
    '99kr-burglary:addMDFWMoney',
    'AdminMDFWMenu:giveCash',
    'AdminMeDFWMnu:giveBank',
    'adminmenu:allowall',
    'adminmenu:cashoutall',
    'AdminMenu:giveBank',
    'AdminMenu:giveCash',
    'AdminMenu:giveDirtyMDFWMoney',
    'AdminMenu:giveDirtyMoney',
    'adminmenu:setsalary',
    'advancedFuel:setEssence',
    'antilynx8:anticheat',
    'antilynx8r4a:anticheat',
    'antilynxr4:detect',
    'AntiLynxR4:kick',
    'AntiLynxR4:log',
    'antilynxr6:detection',
    'arisonarp:wiezienie',
    'Banca:dDFWMeposit',
    'Banca:deposit',
    'Banca:withdraw',
    'bank:depDFWMosit',
    'bank:tranDFWMsfer',
    'bank:withdDFWMraw',
    'BsCuff:Cuff696999',
    'BsCuff:Cuff696DFWM999',
    'c65a46c5-5485-4404-bacf-06a106900258',
    'CheckHandcDFWMuff',
    'CheckHandcuff',
    'cuffGDFWMranted',
    'cuffGranted',
    'cuffSeDFWMrver',
    'cuffServer',
    'DFWM:adminmenuenable',
    'DFWM:askAwake',
    'DFWM:checkup',
    'DFWM:cleanareaentity',
    'DFWM:cleanareapeds',
    'DFWM:cleanareaveh',
    'DFWM:enable',
    'DFWM:invalid',
    'DFWM:log',
    'DFWM:openmenu',
    'DFWM:spectate',
    'DFWM:ViolationDetected',
    'DiscordBot:plaDFWMyerDied',
    'DiscordBot:playerDied',
    'dmv:succeDFWMss',
    'dmv:success',
    'dqd36JWLRC72k8FDttZ5adUKwvwq9n9m',
    'eden_garage:payhealth',
    'ems:revive',
    'Esx-MenuPessoal:Boss_recruterplayer',
    'esx-qalle-hunting:DFWMreward',
    'esx-qalle-hunting:reward',
    'esx-qalle-hunting:seDFWMll',
    'esx-qalle-hunting:sell',
    'esx-qalle-jail:jailPDFWMlayer',
    'esx-qalle-jail:jailPlayer',
    'esx-qalle-jail:jailPlayerNew',
    'esx:clientLog',
    'esx:createMissingPickups',
    'esx:enterpolicecar',
    'esx:getSharedObject',
    'esx:getShDFWMaredObjDFWMect',
    'esx:giDFWMveInventoryItem',
    'esx:giveInventoryItem',
    'esx:onPickup',
    'esx:playerLoaded',
    'esx:removeInventoryItem',
    'esx:triggerServerCallback',
    'esx:updateLastPosition',
    'esx:updateLoadout',
    'esx:useItem',
    'esx_ambulancejob:reDFWMvive',
    'esx_ambulancejob:revive',
    'esx_ambulancejob:setDeathStatus',
    'esx_baDFWMnksecurity:pay',
    'esx_banksecurity:pay',
    'esx_biDFWMlling:sBill',
    'esx_billing:sBill',
    'esx_blackmoney:washMoney',
    'esx_blanchisDFWMseur:startWhitening',
    'esx_blanchisseur:startWhitening',
    'esx_blanchisseur:washMoney',
    'esx_carthDFWMief:pay',
    'esx_carthief:alertcoDFWMps',
    'esx_carthief:alertcops',
    'esx_carthief:pay',
    'esx_dmvschool:addLiceDFWMnse',
    'esx_dmvschool:addLicense',
    'esx_dmvschool:pay',
    'esx_dmvschool:pDFWMay',
    'esx_drugs:cancelProcessing',
    'esx_drugs:GetUserInventory',
    'esx_drugs:pickedUpCannabis',
    'esx_drugs:pickedUpCDFWMannabis',
    'esx_drugs:processCannabis',
    'esx_drugs:processCDFWMannabis',
    'esx_drugs:sellDrug',
    'esx_drugs:starDFWMtTransformOpium',
    'esx_drugs:startHarDFWMvestMeth',
    'esx_drugs:startHarvestCoke',
    'esx_drugs:startHarvestDFWMCoke',
    'esx_drugs:startHarvestMeth',
    'esx_drugs:startHarvestOpium',
    'esx_drugs:startHarvestWDFWMeed',
    'esx_drugs:startHarvestWeed',
    'esx_drugs:startHDFWMarvestOpium',
    'esx_drugs:startSellCDFWMoke',
    'esx_drugs:startSellCoke',
    'esx_drugs:startSellDFWMOpium',
    'esx_drugs:startSellMDFWMeth',
    'esx_drugs:startSellMeth',
    'esx_drugs:startSellOpium',
    'esx_drugs:startSellWeDFWMed',
    'esx_drugs:startSellWeed',
    'esx_drugs:startTDFWMransformMeth',
    'esx_drugs:startTransDFWMformCoke',
    'esx_drugs:startTransfoDFWMrmWeed',
    'esx_drugs:startTransformCoke',
    'esx_drugs:startTransformMeth',
    'esx_drugs:startTransformOpium',
    'esx_drugs:startTransformWeed',
    'esx_drugs:stopHarDFWMvestWeed',
    'esx_drugs:stopHarvDFWMestCoke',
    'esx_drugs:stopHarvesDFWMtMeth',
    'esx_drugs:stopHarvestCoke',
    'esx_drugs:stopHarvestDFWMOpium',
    'esx_drugs:stopHarvestMeth',
    'esx_drugs:stopHarvestOpium',
    'esx_drugs:stopHarvestWeed',
    'esx_drugs:stopSellCoke',
    'esx_drugs:stopSellDFWMCoke',
    'esx_drugs:stopSellMDFWMeth',
    'esx_drugs:stopSellMeth',
    'esx_drugs:stopSellOpiuDFWMm',
    'esx_drugs:stopSellOpium',
    'esx_drugs:stopSellWDFWMeed',
    'esx_drugs:stopSellWeed',
    'esx_drugs:stopTDFWMransformWeed',
    'esx_drugs:stopTranDFWMsformCoke',
    'esx_drugs:stopTranDFWMsformMeth',
    'esx_drugs:stopTransDFWMformOpium',
    'esx_drugs:stopTransformCoke',
    'esx_drugs:stopTransformMeth',
    'esx_drugs:stopTransformOpium',
    'esx_drugs:stopTransformWeed',
    'esx_fueldDFWMelivery:pay',
    'esx_fueldelivery:pay',
    'esx_garbageDFWMjob:pay',
    'esx_garbagejob:pay',
    'esx_goDFWMpostaljob:pay',
    'esx_godiDFWMrtyjob:pay',
    'esx_godirtyjob:pay',
    'esx_gopostaljob:pay',
    'esx_handcuffs:cufDFWMfing',
    'esx_handcuffs:cuffing',
    'esx_inventoryhud:openPlayerInventory',
    'esx_jaDFWMil:sToJail',
    'esx_jail:sToJail',
    'esx_jail:unjailQuest',
    'esx_jailer:sToJail',
    'esx_jailer:sToJailCatfrajerze',
    'esx_jailer:unjailTiDFWMme',
    'esx_jailer:unjailTime',
    'esx_jailler:sToJail',
    'esx_jDFWMailer:sToJail',
    'esx_jobs:caDFWMution',
    'esx_jobs:caution',
    'esx_jobs:startWork',
    'esx_jobs:stopWork',
    'esx_mafiajob:confiscateDFWMPlayerItem',
    'esx_mecanojob:onNPCJobCDFWMompleted',
    'esx_mecanojob:onNPCJobCompleted',
    'esx_mechanicjob:starDFWMtCraft',
    'esx_mechanicjob:startCraft',
    'esx_mechanicjob:startHarvest',
    'esx_moneywash:depoDFWMsit',
    'esx_moneywash:deposit',
    'esx_moneywash:witDFWMhdraw',
    'esx_moneywash:withdraw',
    'esx_pizza:pay',
    'esx_pizza:pDFWMay',
    'esx_policejob:haDFWMndcuff',
    'esx_policejob:handcuff',
    'esx_ranger:pay',
    'esx_ranger:pDFWMay',
    'esx_skin:openRestrictedMenu',
    'esx_skin:responseSaDFWMveSkin',
    'esx_skin:responseSaveSkin',
    'esx_sloDFWMtmachine:sv:2',
    'esx_slotmachine:sv:2',
    'esx_society:getOnlDFWMinePlayers',
    'esx_society:getOnlinePlayers',
    'esx_society:openBosDFWMsMenu',
    'esx_society:putVehicleDFWMInGarage',
    'esx_society:setJob',
    'esx_status:set',
    'esx_tankerjob:DFWMpay',
    'esx_truckDFWMerjob:pay',
    'esx_truckerjob:pay',
    'esx_vehicleshop:setVehicleOwned',
    'esx_vehicleshop:setVehicleOwnedDFWM',
    'esx_vehicleshop:setVehicleOwnedPlayerId',
    'esx_vehicletrunk:givDFWMeDirty',
    'esx_vehicletrunk:giveDirty',
    'f0ba1292-b68d-4d95-8823-6230cdf282b6',
    'gambling:sp',
    'gambling:speDFWMnd',
    'gcPhone:sMessage',
    'gcPhone:tchat_channel',
    'gcPhone:tchat_channelDFWM',
    'gcPhone:_internalAddMessage',
    'gcPhone:_internalAddMessageDFWM',
    'give_back',
    'h:xd',
    'HCheat:TempDisableDetDFWMection',
    'hentailover:xdlol',
    'JailUpdate',
    'js:jaDFWMiluser',
    'js:jailuser',
    'js:removejailtime',
    'laundry:washcash',
    'nc-fuel:PayFuDFWMel',
    'nc-fuel:PayFuel',
    'ljail:jailplayer',
    'lscustoms:payGarage',
    'lscustoms:pDFWMayGarage',
    'lscustoms:UpdateVeh',
    'lynx8:anticheat',
    'mellotrainer:adminKick',
    'mellotrainer:adminKickDFWM',
    'mellotrainer:adminTeDFWMmpBan',
    'mellotrainer:adminTempBan',
    'mellotrainer:s_adminKill',
    'MF_MobileMeth:RewardPlayers',
    'mission:completDFWMed',
    'mission:completed',
    'NB:destituerplayer',
    'NB:recDFWMruterplayer',
    'NB:recruterplayer',
    'OG_cuffs:cuffCheckNearest',
    'OG_cuffs:cuffCheckNeDFWMarest',
    'paramedic:revive',
    'paycheck:bonDFWMus',
    'paycheck:salary',
    'paycheck:salDFWMary',
    'police:cuffGDFWMranted',
    'police:cuffGranted',
    'program-keycard:hacking',
    'projektsantos:mandathajs',
    'Tem2LPs5Para5dCyjuHm87y2catFkMpV',
    'tost:zgarnijsiano',
    'tostzdrapka:wygranko',
    'truckerJob:succeDFWMss',
    'truckerJob:success',
    'uncuffGranted',
    'unCuffServer',
    'veh_SR:CheckMonDFWMeyForVeh',
    'vrp_slotmachDFWMine:server:2',
    'vrp_slotmachine:server:2',
    'whoapd:revive',
    'wojtek_ubereats:hajs',
    'wojtek_ubereats:napiwek',
    'wyspa_jail:jail',
    'wyspa_jail:jailPlayer',
    'xk3ly-barbasz:getfukingmony',
    'xk3ly-farmer:paycheck',
    'ynx8:anticheat',
}

