Config = {}

Config.VendingObjects = {
    "prop_vend_soda_01",
    "prop_vend_soda_02",
    "prop_vend_water_01"
}

Config.BinObjects = {
    "prop_bin_05a",
}

Config.CraftingObject = `prop_toolchest_05` -- Only needed if not using target | Line 928 to change Target Models

Config.VendingItem = {
    [1] = {
        name = "kurkakola",
        price = 4,
        amount = 50,
        info = {},
        type = "item",
        slot = 1,
    },
    [2] = {
        name = "water_bottle",
        price = 4,
        amount = 50,
        info = {},
        type = "item",
        slot = 2,
    },
}

Config.CraftingItems = {
    [1] = {
        name = "pistol_extendedclip",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 75,
            ["steel"] = 75,
            ["aluminum"] = 75,
            ["plastic"] = 75,
        },
        type = "item",
        slot = 1,
        threshold = 0,
        points = 1,
    },
    [2] = {
        name = "pistol_flashlight",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 75,
            ["steel"] = 75,
            ["aluminum"] = 75,
            ["plastic"] = 75,
        },
        type = "item",
        slot = 2,
        threshold = 0,
        points = 2,
    },
    [3] = {
        name = "pistol_suppressor",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 75,
            ["steel"] = 75,
            ["aluminum"] = 75,
            ["plastic"] = 75,
        },
        type = "item",
        slot = 3,
        threshold = 0,
        points = 3,
    },
    [4] = {
        name = "smg_extendedclip",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 100,
            ["steel"] = 100,
            ["aluminum"] = 100,
            ["plastic"] = 100,
        },
        type = "item",
        slot = 4,
        threshold = 0,
        points = 4,
    },
    [5] = {
        name = "smg_drum",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 100,
            ["plastic"] = 100,
            ["aluminum"] = 100,
            ["steel"] = 100,
        },
        type = "item",
        slot = 5,
        threshold = 0,
        points = 0,
    },
    [6] = {
        name = "smg_scope",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 100,
            ["steel"] = 100,
            ["aluminum"] = 100,
            ["plastic"] = 100,
        },
        type = "item",
        slot = 6,
        threshold = 0,
        points = 0,
    },
    [7] = {
        name = "smg_suppresor",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 100,
            ["steel"] = 100,
            ["plastic"] = 100,
            ["aluminum"] = 100,
        },
        type = "item",
        slot = 7,
        threshold = 0,
        points = 0,
    },
    [8] = {
        name = "smg_flashlight",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 100,
            ["steel"] = 100,
            ["plastic"] = 100,
            ["aluminum"] = 100,
        },
        type = "item",
        slot = 8,
        threshold = 0,
        points = 0,
    },
    [9] = {
        name = "rifle_flashlight",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 125,
            ["steel"] = 125,
            ["plastic"] = 125,
            ["aluminum"] = 125,
        },
        type = "item",
        slot = 9,
        threshold = 0,
        points = 0,
    },
    [10] = {
        name = "rifle_extendedclip",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 125,
            ["steel"] = 125,
            ["plastic"] = 125,
            ["aluminum"] = 125,
        },
        type = "item",
        slot = 10,
        threshold = 0,
        points = 0,
    },
    [11] = {
        name = "rifle_suppressor",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 125,
            ["steel"] = 125,
            ["plastic"] = 125,
            ["aluminum"] = 125,
        },
        type = "item",
        slot = 11,
        threshold = 0,
        points = 0,
    },
    [12] = {
        name = "rifle_drummag",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 125,
            ["steel"] = 125,
            ["plastic"] = 125,
            ["aluminum"] = 125,
        },
        type = "item",
        slot = 12,
        threshold = 0,
        points = 0,
    },
    [13] = {
        name = "rifle_scope",
        amount = 50,
        info = {},
        costs = {
            ["metalscrap"] = 125,
            ["steel"] = 125,
            ["plastic"] = 125,
            ["aluminum"] = 125,
        },
        type = "item",
        slot = 13,
        threshold = 0,
        points = 0,
    },
}

Config.AttachmentCraftingLocation = vector3(-401.23, 181.32, 80.25) -- Only needed if not using target

Config.AttachmentCrafting = {
    ["items"] = {
        [1] = {
            name = "lockpick",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["steel"] = 100,
                ["rubber"] = 100,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = "advancedlockpick",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 120,
                ["steel"] = 120,
                ["rubber"] = 120,
            },
            type = "item",
            slot = 2,
            threshold = 0,
            points = 2,
        },
        [3] = {
            name = "bag",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 125,
                ["steel"] = 125,
                ["rubber"] = 125,
                ["glass"] = 125,
            },
            type = "item",
            slot = 3,
            threshold = 0,
            points = 3,
        },
        [4] = {
            name = "drill",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 170,
                ["steel"] = 170,
                ["rubber"] = 170,
                ["glass"] = 170,
            },
            type = "item",
            slot = 4,
            threshold = 0,
            points = 4,
        },
        [5] = {
            name = "big_drill",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 180,
                ["steel"] = 180,
                ["rubber"] = 180,
                ["glass"] = 180,
            },
            type = "item",
            slot = 5,
            threshold = 0,
            points = 5,
        },
        [6] = {
            name = "trojan_usb",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 140,
                ["steel"] = 140,
                ["rubber"] = 140,
                ["glass"] = 140,
            },
            type = "item",
            slot = 6,
            threshold = 0,
            points = 6,
        },
        [7] = {
            name = "electronickit",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 145,
                ["steel"] = 145,
                ["rubber"] = 145,
                ["glass"] = 145,
            },
            type = "item",
            slot = 7,
            threshold = 0,
            points = 7,
        },
        [8] = {
            name = "vpn",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 155,
                ["steel"] = 155,
                ["rubber"] = 155,
                ["glass"] = 155,
            },
            type = "item",
            slot = 8,
            threshold = 0,
            points = 8,
        },
        [9] = {
            name = "c4_bomb",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 190,
                ["steel"] = 190,
                ["rubber"] = 190,
                ["glass"] = 190,
            },
            type = "item",
            slot = 9,
            threshold = 0,
            points = 9,
        },
        [10] = {
            name = "laptop",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 150,
                ["steel"] = 150,
                ["rubber"] = 150,
                ["glass"] = 150,
            },
            type = "item",
            slot = 10,
            threshold = 0,
            points = 10,
        },
        [11] = {
            name = "thermite",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 130,
                ["steel"] = 130,
                ["rubber"] = 130,
                ["glass"] = 130,
            },
            type = "item",
            slot = 11,
            threshold = 0,
            points = 11,
        },
        [12] = {
            name = "cutter",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 140,
                ["steel"] = 140,
                ["rubber"] = 140,
                ["glass"] = 140,
            },
            type = "item",
            slot = 12,
            threshold = 0,
            points = 12,
        },
        [13] = {
            name = "gatecrack",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 167,
                ["steel"] = 167,
                ["rubber"] = 167,
                ["glass"] = 167,
            },
            type = "item",
            slot = 13,
            threshold = 0,
            points = 13,
        },
        [14] = {
            name = "blowtorch",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 143,
                ["steel"] = 143,
                ["rubber"] = 143,
                ["glass"] = 143,
            },
            type = "item",
            slot = 14,
            threshold = 0,
            points = 14,
        },
        [15] = {
            name = "screwdriverset",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 114,
                ["steel"] = 114,
                ["rubber"] = 114,
                ["glass"] = 114,
            },
            type = "item",
            slot = 15,
            threshold = 0,
            points = 15,
        },
        [16] = {
            name = "hack_usb",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 140,
                ["steel"] = 140,
                ["rubber"] = 140,
                ["glass"] = 140,
            },
            type = "item",
            slot = 16,
            threshold = 0,
            points = 16,
        },
        [17] = {
            name = "cg_chain",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 17,
            threshold = 0,
            points = 17,
        },
        [18] = {
            name = "cerberus_chain",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 18,
            threshold = 0,
            points = 18,
        },
        [19] = {
            name = "mdm_chain",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 19,
            threshold = 0,
            points = 19,
        },
        [20] = {
            name = "esv_chain",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 20,
            threshold = 0,
            points = 20,
        },
        [21] = {
            name = "koil_chain",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 21,
            threshold = 0,
            points = 21,
        },
        [22] = {
            name = "gsf_chain",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 22,
            threshold = 0,
            points = 22,
        },
        [23] = {
            name = "black_usb",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 23,
            threshold = 0,
            points = 23,
        },
        [24] = {
            name = "radioscanner",
            amount = 5,
            info = {},
            costs = {
                ["metalscrap"] = 250,
                ["steel"] = 250,
                ["rubber"] = 250,
                ["glass"] = 250,
            },
            type = "item",
            slot = 24,
            threshold = 0,
            points = 24,
        },
    }
}

MaxInventorySlots = 41

BackEngineVehicles = {
    [`ninef`] = true,
    [`adder`] = true,
    [`vagner`] = true,
    [`t20`] = true,
    [`infernus`] = true,
    [`zentorno`] = true,
    [`reaper`] = true,
    [`comet2`] = true,
    [`comet3`] = true,
    [`jester`] = true,
    [`jester2`] = true,
    [`cheetah`] = true,
    [`cheetah2`] = true,
    [`prototipo`] = true,
    [`turismor`] = true,
    [`pfister811`] = true,
    [`ardent`] = true,
    [`nero`] = true,
    [`nero2`] = true,
    [`tempesta`] = true,
    [`vacca`] = true,
    [`bullet`] = true,
    [`osiris`] = true,
    [`entityxf`] = true,
    [`turismo2`] = true,
    [`fmj`] = true,
    [`re7b`] = true,
    [`tyrus`] = true,
    [`italigtb`] = true,
    [`penetrator`] = true,
    [`monroe`] = true,
    [`ninef2`] = true,
    [`stingergt`] = true,
    [`surfer`] = true,
    [`surfer2`] = true,
    [`gp1`] = true,
    [`autarch`] = true,
    [`tyrant`] = true
}

Config.MaximumAmmoValues = {
    ["pistol"] = 250,
    ["smg"] = 250,
    ["shotgun"] = 200,
    ["rifle"] = 250,
}
