

-- Mach created by King˳Hunter18
Config.DoorList['catcafe1'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 89.99,
    garage = false,
    objHash = -1283712428,
    fixText = false,
    objCoords = vector3(-587.34, -1051.899, 22.41301),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe2'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 89.99,
    garage = false,
    objHash = 2089009131,
    fixText = false,
    objCoords = vector3(-594.4123, -1049.769, 22.49713),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe3'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 179.99,
    garage = false,
    objHash = -60871655,
    fixText = false,
    objCoords = vector3(-590.1828, -1054.148, 22.41301),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe4'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 0.0,
    garage = false,
    objHash = -60871655,
    fixText = false,
    objCoords = vector3(-592.4738, -1056.091, 22.41301),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe5'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 269.99,
    garage = false,
    objHash = 1099436502,
    fixText = false,
    objCoords = vector3(-600.8886, -1055.131, 22.71303),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe6'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 270.00,
    garage = false,
    objHash = 522844070,
    fixText = false,
    objCoords = vector3(-600.9106, -1059.218, 21.72342),
    maxDistance = 5.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe7'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 0.0,
    garage = false,
    objHash = 2089009131,
    fixText = false,
    objCoords = vector3(-571.7927, -1057.388, 26.76797),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe8'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 270.00,
    garage = false,
    objHash = 2089009131,
    fixText = false,
    objCoords = vector3(-575.0109, -1062.381, 26.76797),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['catcafe9'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['catcafe']=0 },
    objHeading = 89.99,
    garage = false,
    objHash = 2089009131,
    fixText = false,
    objCoords = vector3(-575.0128, -1063.783, 26.76797),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}