

-- Mach created by King˳Hunter18
Config.DoorList['pizza1'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 180.12,
    garage = false,
    objHash = 1984391163,
    fixText = false,
    objCoords = vector3(806.2781, -765.8099, 26.93464),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['pizza2'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 89.99,
    garage = false,
    objHash = 1984391163,
    fixText = false,
    objCoords = vector3(811.9174, -762.428, 26.93464),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['pizza3'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 89.98,
    garage = false,
    objHash = -420112688,
    fixText = false,
    objCoords = vector3(814.5675, -762.8239, 27.04651),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['pizza4'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 180.141,
    garage = false,
    objHash = 1984391163,
    fixText = false,
    objCoords = vector3(797.4042, -758.2521, 31.41847),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['pizza5'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 0.12,
    garage = false,
    objHash = 1984391163,
    fixText = false,
    objCoords = vector3(798.6847, -763.329, 31.41847),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['pizza6'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 270.19,
    garage = false,
    objHash = 1984391163,
    fixText = false,
    objCoords = vector3(806.8858, -764.5674, 31.41847),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['pizza7'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 270.07,
    garage = false,
    objHash = 1984391163,
    fixText = false,
    objCoords = vector3(804.4858, -767.6975, 31.41847),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['pizza8'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['pizzathis']=0 },
    objHeading = 359.86,
    garage = false,
    objHash = 1984391163,
    fixText = false,
    objCoords = vector3(810.4092, -756.2733, 26.93464),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}