

-- Mach created by King˳Hunter18
Config.DoorList['vanilla1'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['vanilla']=0 },
    objHeading = 30.16,
    garage = false,
    objHash = -1116041313,
    fixText = false,
    objCoords = vector3(127.9501, -1298.507, 29.41962),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['vanilla2'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['vanilla']=0 },
    objHeading = 29.99,
    garage = false,
    objHash = 1695461688,
    fixText = false,
    objCoords = vector3(132.211, -1288.254, 29.43619),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['vanilla3'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['vanilla']=0 },
    objHeading = 210.0,
    garage = false,
    objHash = 1695461688,
    fixText = false,
    objCoords = vector3(128.0708, -1279.347, 29.43697),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['vanilla4'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['vanilla']=0 },
    objHeading = 300.0,
    garage = false,
    objHash = 390840000,
    fixText = false,
    objCoords = vector3(116.2278, -1294.593, 29.43599),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['vanilla5'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['vanilla']=0 },
    objHeading = 300.0,
    garage = false,
    objHash = 390840000,
    fixText = false,
    objCoords = vector3(113.4101, -1296.26, 29.43599),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['vanilla6'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['vanilla']=0 },
    objHeading = 29.99,
    garage = false,
    objHash = 390840000,
    fixText = false,
    objCoords = vector3(99.08307, -1293.689, 29.4404),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}
Config.DoorList['vanilla7'] = {
    lockpick = false,
    audioRemote = false,
    locked = true,
    authorizedJobs = { ['vanilla']=0 },
    objHeading = 210.0,
    garage = false,
    objHash = 1695461688,
    fixText = false,
    objCoords = vector3(96.09197, -1284.854, 29.43878),
    maxDistance = 2.0,
    slides = false,
    --oldMethod = true,
    --audioLock = {['file'] = 'metal-locker.ogg', ['volume'] = 0.6},
    --audioUnlock = {['file'] = 'metallic-creak.ogg', ['volume'] = 0.7},
    --autoLock = 1000,
    --doorRate = 1.0,
    --showNUI = true
}